language: python
sudo: required
python: 2.7
services: postgresql
before_install: sudo apt-get install libpq-dev python-dev
install:
  - pip install -r requirements/requirements-base.txt
  - pip install -r requirements/requirements-tests.txt
before_script: ./build_travis_settings.sh
script: py.test -sv
