version: '3'
services:
  default-db-dev:
    image: mariadb:10.3
    environment:
      - MYSQL_USER=${DEFAULT_DB_USER}
      - MYSQL_PASSWORD=${DEFAULT_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DEFAULT_DB_PASSWORD}
      - MYSQL_DATABASE=${DEFAULT_DB_NAME:-django_catalog_api}
    ports:
      - "${DEFAULT_DB_HOST:-127.0.0.1}:${DEFAULT_DB_PORT:-3306}:3306"
    volumes:
      - ./docker_data/default_db_dev:/var/lib/mysql
    networks:
      - development

  default-db-test:
    image: mariadb:10.3
    environment:
      - MYSQL_USER=${TEST_DEFAULT_DB_USER}
      - MYSQL_PASSWORD=${TEST_DEFAULT_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${TEST_DEFAULT_DB_PASSWORD}
      - MYSQL_DATABASE=${TEST_DEFAULT_DB_NAME:-capi_test}
    ports:
      - "${TEST_DEFAULT_DB_HOST:-127.0.0.1}:${TEST_DEFAULT_DB_PORT:-3307}:3306"
    volumes:
      - ./docker_data/default_db_test:/var/lib/mysql
    networks:
      - testing

  sierra-db-test:
    image: postgres:9.2
    environment:
      - POSTGRES_USER=${TEST_SIERRA_DB_USER}
      - POSTGRES_PASSWORD=${TEST_SIERRA_DB_PASSWORD}
      - POSTGRES_DB=${TEST_SIERRA_DB_NAME:-sierra_test}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${TEST_SIERRA_DB_HOST:-127.0.0.1}:${TEST_SIERRA_DB_PORT:-5432}:5432"
    volumes:
      - ./docker_data/sierra_db_test:/var/lib/postgresql/data/pgdata
    networks:
      - testing

  app:
    build: .
    depends_on:
      - default-db-dev
    volumes:
      - .:/project/catalog-api
    networks:
      - testing
      - development
    ports:
      - "${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}"

  test:
    build: .
    depends_on:
      - default-db-test
      - sierra-db-test
    volumes:
      - .:/project/catalog-api
    networks:
      - testing
    entrypoint: wait-for-it.sh -t 0 default-db-test:3306 -- wait-for-it.sh -t 0 sierra-db-test:5432 -- py.test

  manage-dev:
    build: .
    depends_on:
      - default-db-dev
    volumes:
      - .:/project/catalog-api
    networks:
      - development
    working_dir: /project/catalog-api/django/sierra
    entrypoint: wait-for-it.sh -t 0 default-db-dev:3306 -- /project/catalog-api/django/sierra/manage.py

  manage-test:
    build: .
    depends_on:
      - default-db-test
      - sierra-db-test
    volumes:
      - .:/project/catalog-api
    networks:
      - testing
    working_dir: /project/catalog-api/django/sierra
    environment:
      - DJANGO_SETTINGS_MODULE=sierra.settings.test
    entrypoint: wait-for-it.sh -t 0 default-db-test:3306 -- wait-for-it.sh -t 0 sierra-db-test:5432 -- /project/catalog-api/django/sierra/manage.py


networks:
  development:
  testing:
